config/routes.rb
Rails.application.routes.draw do
  resources :teams
  post    '/teams/:id',   to: 'teams#change_players'
  resources :users do
  	member do
  	 	get 'teams'
 	end
  end
  resources :players
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	validates :file, presence: true
	validates :element, presence: true
	validates :star, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  has_many :players

  validates :players, length: { maximum: 10 }
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :teams
  
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  #allows pictures using paperclip and some validations
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, 
  :default_url => ':style/blank_profile_pic.png'
  validates_attachment :avatar,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def index
    	@players = Player.all
  	end

	def show
    	@player = Player.find(params[:id])
  	end

	def new
		@player = Player.new
	end

	def edit
  		@player = Player.find(params[:id])
	end

	def create
  		@player = Player.new(player_params)
 
	  	if @player.save
  			redirect_to @player
		else 
			render 'new'
		end
	end

	def update
  		@player = Player.find(params[:id])
 
  		if @player.update(player_params)
   			redirect_to @player
  		else
    	render 'edit'
  		end
	end

	def destroy
   		@player = Player.find(params[:id])
   		@player.destroy
 
    	redirect_to players_path
  	end

	private 
		def player_params
			params.require(:player).permit(:name, :file, :element, :star)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
    flash[:success] = "You have logged out successfully"
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	
	def index
    	@teams = Team.all
  	end

	def show
    	@team = Team.find(params[:id])
  	end

	def new
		if !logged_in?
      		flash[:danger] = "Not logged in"
      		redirect_to login_path
      	end
		@team = Team.new
	end

	def edit
  		@team = Team.find(params[:id])
	end

	def create
  		@team = Team.new(team_params)
  		@team.user = current_user
  		(0..9).each do |i|
  			@team.players << Player.find_by(file: "Default" + i.to_s + ".png")
 		end
	  	if @team.save
  			redirect_to @team
		else 
			render 'new'
		end
	end

	def update
  		@team = Team.find(params[:id])

  		if @team.update(team_params)
   			redirect_to @team
  		else
    	render 'edit'
  		end
	end

	def change_players
		i = 0
		params.require(:team).permit(:players => [])
		@team = Team.find(params[:id])
		@players = params[:team][:players] 
		@team.players.delete_all
		@players.each do |player|
			if Player.find_by(file: player + ".png").nil? == true
				i+= 1
			else @team.players << Player.find_by(file: player +".png")
			end
		if i > 0
			(0..9).each do |count|
				if @team.players.length < 10 
					@team.players << Player.find_by(file: "default" + count.to_s + ".png")
				end
			end
		end

		end
		redirect_to @team
	end


	def destroy
   		@team = Team.find(params[:id])
   		@team.destroy
 
    	redirect_to teams_path
  	end

	private 
		def team_params
			params.require(:team).permit(:title, :text)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome"
      redirect_to @user
    else
      render 'new'
    end
  end

    def update
      @user = User.find(params[:id])
 
      if @user.update(user_params)
        redirect_to @user
      else
      render 'edit'
      end
  end

  def teams
    @teams = User.find(params[:id]).teams
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

# Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

# Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

# Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Formation by <a href="https://github.com/driedmangoe">driedmangoe</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
       <li><%= link_to "News", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Formation", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Teams", teams_path %></li>
        <% if logged_in? %>
          <li><%= link_to "My Teams", teams_user_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>        
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_team_form_card.html.erb
<%-#layout for the cards formation area on the new team page-%>
<div class="row">
  <%-#set id for cards-%>
  <% id = 0 %> 
  <% position = "front" %>
  <% (0..2).each do |i| %>
    <div class="col-md-4">
      <% (0..2).each do |j| %>
        <br>
        <%= image_tag("characters/" + @team.players[id+(j*3)].file, :alt => "rss feed" , :class => ["displayed" , "character-image-size", "card"], :id => id+(j*3), :value => @team.players[id+(j*3)].name)%>
        <% if j == 0 %>
          <center> front </center>
        <% end %>
        <% if j == 1 %>
           <center> mid </center>
        <% end %>
        <% if j == 2 %>
           <center> bot </center>
        <% end %>
      <% end %>
    </div> 
    <% id += 1 %>
  <% end %>
</div>

app/views/layouts/_team_pick_players.html.erb
<%-#layout for the 'pick players' area on the right side of the new team page-%>
<br>
<br>
<br>
<div class= "row">	
  <div class="tab-pane">
  <% player = 0 %>  
  <%-# the - 10 accounts for the 10 blank player defaults-%>
  <%-# Skip if default player so it doesnt display 10 blank photos in selection-%>
  <% n = Player.count-10 %>
  <% if n <= 3%>
    <% (0..2).each do |i| %>
    <% p = Player.find_by(id: (i + 1)) %> 
    <% next if p.star == 1 %>
      <div class="col-md-4">
        <br>
          <%= image_tag("characters/" + p.file, :alt => "rss feed" , :class => ["displayed" , "character-image-size", "pick"], :id => "player" + i.to_s) %>
          <%=  i%>
      </div>
    <% end %>
  <% end %>
  <% if n > 3%>
    <% (0..2).each do |i| %>
      <div class="col-md-4">
      <% (0..(n/3).floor).each do |j| %>
      <% next if player+(j*3)+1 > Player.count %>  
      <% p = Player.find_by(id: (player+(j*3)+1)) %> 
      <% next if p.star == 1 %>  
          <br>
          <%= image_tag("characters/" + p.file, :alt => "rss feed" , :class => ["displayed" , "character-image-size", "pick"], :id => "player" + (player + j).to_s, :name => p.file[0..(p.file.length-5)]) %>
      <% end %>
      </div> 
      <% player += 1 %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formation</title>
	<%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/players/index.html.erb
<h1>Listing Players</h1>

<table>
  <tr>
    <th>player</th>
    <th>star</th>
  </tr>
 
  <% @players.each do |player| %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.star %></td>
      <td><%= player.file %></td>
      <td><%= link_to 'Show', player_path(player) %></td>
    </tr>
  <% end %>
</table>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= form_for :player, url: players_path do |f| %>

  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@player.errors.count, "error") %> prohibited
        this player from being saved:
      </h2>
      <ul>
        <% @player.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :file %><br>
    <%= f.text_field :file
     %>
  </p>

  <p>
    <%= f.label :element %><br>
    <%= f.text_field :element %>
  </p>

   <p>
    <%= f.label :star %><br>
    <%= f.text_field :star %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p>
  <strong>Player:</strong>
  <%= @player.name %>
</p>
 
<p>
  <strong>file:</strong>
  <%= @player.file %>
</p>

<p>
  <strong>element:</strong>
  <%= @player.element %>
</p>

<p>
  <strong>star:</strong>
  <%= @player.star %>
</p>

<%= image_tag "characters/" + @player.file %> 

<br>

<%= link_to 'Back', players_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for @user, url: user_path, method: :PATCH, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :avatar %>
      <%= f.file_field :avatar %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Edit", class: "btn btn-primary" %>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<table>
  <tr>
    <th>User</th>
    <th>email</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: users_path, html: { multipart: true }) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :avatar %>
      <%= f.file_field :avatar %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p>
  <strong>User:</strong>
  <%= @user.name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= image_tag @user.avatar.url(:medium) %> 
<br>

<% if logged_in? %>
<%= link_to 'edit', edit_user_path(@user) %>
<% end %>
<%= link_to 'Back', users_path %>

app/views/users/teams.html.erb
<h1>Listing Your teams</h1>
<%= link_to 'New team', new_team_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @teams.each do |team| %>
    <tr>
      <td><%= team.title %></td>
      <td><%= team.text %></td>
      <td><%= link_to 'Show', team_path(team) %></td>
      <td><%= link_to 'Edit', edit_team_path(team) %></td>
    </tr>
  <% end %>
</table>

app/views/welcome/index.html.erb
<h1>Welcome to Soccer Spirits Formation Builder</h1>
<br>
<br>
<br>
<%= image_tag("ss_logo.jpg", :alt => "rss feed" , :class => ["displayed , welcome-image-size"]) %>
 